/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

public class App {
    public Bitmap bit = new Bitmap();
    public static void main(String[] args) {
        String gray = "gray";
        String glow = "glow";
        String green = "green";

        if (args[0].equals(gray)) {
            Bitmap img = new Bitmap();
            img.grayUp(img.ogFilePath);
        } else if (args[0].equals(glow)) {
            Bitmap img = new Bitmap();
            img.glowUp(img.ogFilePath);
        } else if (args[0].equals(green)) {
            Bitmap img = new Bitmap();
            img.greenUp(img.ogFilePath);
        }
    }
}
